languaje: groovy

jdk:
- oraclejdk7

before_script:
- chmod +x ./grailsw

script: 
- "./grailsw refresh-dependencies --non-interactive"
- "./grailsw compile --non-interactive"
- "./grailsw dev war --non-interactive webapps/ROOT.war"

before_deploy:
- git config --global user.email 'bot@travis-ci.com'
- git config --global user.name 'Bot - Travis CI'
- git checkout $TRAVIS_BRANCH
- git add -f webapps/*
- git commit -am '[Travis] Deploy'

deploy:
  provider: openshift
  user: ja.rodriguez.vazquez@gmail.com
  password:
    secure: 7r7cyRkbR9WKDUpgRP9yiUxvP0GxX7Mo4GI8mngUhb3TD5M/xsmCwtng46Xeq6qua7aon32IfxOQlSwHbQ6uk4P1qW8QPNqlN4YWAQstPCftjTM1mHkq3dJYPgHKB8NshAHHayX4vhApBmKW7MBGuu3lXVbPGp5WduZ5zp3HCAvOXCHfvPrU9amViHV43OAlpOkBm4fMbYGbabzDt3iR59oi16SSMJJAuOy+75gOEIn8fHz/gpa5AiZPae6wvPicZ4JljGTv2vP5z4aLOoh+/CmbCk+Bhar3NxL3qaXpdQ0DQy5yXplcIJEMuBxNkx/aLI4NKKSXvjmi9LtEWInOPZ1KRiWglnuRLNc+iYeG8VB436aulFLc12aXC/ZoS+PqALuDCGFL5EwEO4lLFPCuJ6zguVDzRUOgqFDBxLT71Sy2bwq9+b1tz/vsGqQ8Sl30Kx+caK3IJmIloZoKA7M0t7qZ794gDbcKGF59nUwAu0gZFWLwR/LzVqU3BVx04scg8unrHNUc12WLkBieUxumcgC1jN26v5PyGUHF18SjxswNAPKxP9BRxYnDZpwoONmG0CIXZ2+Mrzh1yww51WyO8iG0rQV4cb16iJ7OP5xd/oTWThDXLk190T76fa0+czaJ6tv8++/U8eLfZpzyLoluUkykESQ8Gsokd7rnxowdMTs=
  app: backend
  domain: tpprofesional
  skip_cleanup: true
  
